### ISSUE TITLE
Mime type error (probably) when HTTP POST on creating new user

### ISSUE THREAD

**Issue by SmartPhoneLover** [Dullage/tahskr-server#6]
Hello, I'm receiving error when doing HTTP POST to create new user.
I think I set all the necessary fields and types of data required to perform a HTTP POST call.

Sending HTTP GET actions, such as the basic one (get release information) works as expected.
I tried to send the calls in local (HTTP) and via reverse proxy (HTTPS), and in bothy situations it fails.

The app that I used to perform the calls is Tasker, and Android app.

![photo_2022-05-19_18-10-49](https://user-images.githubusercontent.com/42898749/169356713-aa9607d2-b90b-4d96-bbf4-f348b8ca1e4d.jpg)
![photo_2022-05-19_18-09-29](https://user-images.githubusercontent.com/42898749/169356721-89f05510-1088-4503-9607-fcb4f3b6990d.jpg)

**Comment by dullage** [comment]
Hi @SmartPhoneLover, the username and password need to be passed as JSON in the **body** of the request. e.g. `{"username": "usuario", "password": "pass"}`. Judging from your screenshot they are currently being passed as query parameters.

Give this a go and let me know how you get on.

**Comment by SmartPhoneLover** [comment]
Now it worked as expected!
Yes, my two errors where, not passing the items as JSON: missing brackets {.} and doble quotes ".".
The other error was the field used.

Thank you very much!
